# Generated by Django 5.2.17 on 2026-09-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanatoriumBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sanatoriya nomi')),
                ('description', models.TextField(verbose_name='Sanatoriya haqida tavsif')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Admin telefon raqami')),
                ('telegram_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Telegram lichkasi')),
                ('instagram_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram profili')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Odam boshiga 1 kunlik to'lov (so'mda)")),
                ('image1', models.ImageField(upload_to='sanatoriums/%Y/%m/', verbose_name='Asosiy rasm')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='sanatoriums/%Y/%m/', verbose_name='2-rasm')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='sanatoriums/%Y/%m/', verbose_name='3-rasm')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='sanatoriums/%Y/%m/', verbose_name='4-rasm')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='sanatoriums/%Y/%m/', verbose_name='5-rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Tahrirlangan vaqti')),
            ],
            options={
                'verbose_name': 'Sanatoriya baneri',
                'verbose_name_plural': 'Sanatoriya banerlari',
            },
        ),
    ]
