# Generated by Django 5.2.17 on 2026-09-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanatoriumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sanatoriya nomi')),
                ('region', models.CharField(max_length=255, verbose_name='Hudud / Viloyat')),
                ('location_url', models.URLField(max_length=500, verbose_name='Xaritadagi joylashuv (URL)')),
                ('description', models.TextField(verbose_name='Sanatoriya haqida tavsif')),
                ('image1', models.ImageField(upload_to='sanatoriums/', verbose_name='Rasm 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='sanatoriums/', verbose_name='Rasm 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='sanatoriums/', verbose_name='Rasm 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='sanatoriums/', verbose_name='Rasm 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='sanatoriums/', verbose_name='Rasm 5')),
                ('phone1', models.CharField(max_length=20, verbose_name='Telefon 1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 2')),
                ('phone3', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 3')),
                ('phone4', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 4')),
                ('phone5', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon 5')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="1 kunlik to'lov")),
                ('advance_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Oldindan to'lov")),
                ('telegram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Telegram')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Veb-sayt')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sanatoriya Profili',
                'verbose_name_plural': 'Sanatoriya Profillari',
            },
        ),
    ]
