# Generated by Django 5.2.17 on 2026-09-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanatoriumprofile',
            name='location_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Xaritadagi joylashuv (URL)'),
        ),
    ]
