class AppStrings {
  static String currentLocale = 'uz';

  static final Map<String, Map<String, String>> _translations = {
    'uz': {
      'welcome': 'Ilovaga Xush kelibsiz',
      'select_language': 'Tilni tanlang',
      'phone_input_title': 'Telefon raqamingizni kiriting',
      'phone_input_subtitle': 'Hisobingizni himoya qilish uchun raqamingiz kerak.',
      'continue': 'Davom etish',
      'otp_title': '6 xonali kodni kiriting',
      'otp_subtitle': 'Tasdiqlash kodi ushbu raqamga yuborildi: ',
      'register_title': 'Ro\'yxatdan o\'tish',
      'first_name': 'Ism',
      'last_name': 'Familiya',
      'province': 'Viloyat',
      'district': 'Tuman',
      'birth_date': 'Tug\'ilgan sana',
      'home': 'Bosh sahifa',
      'appointments': 'Qabulga',
      'messages': 'Xabarlar',
      'profile': 'Profil',
      'settings': 'Sozlamalar',
      'logout': 'Hisobdan chiqish',
      'view_profile': 'Profilni ko\'rish',
      'personal_info': 'Shaxsiy ma\'lumotlar',
      'payments': 'To\'lovlar',
      'security': 'Xavfsizlik',
      'change_language': 'Tilni o\'zgartirish',
      'help': 'Yordam',
      'messages_empty_title': 'Xabarlar topilmadi!',
      'messages_empty_desc': 'Hozircha sizda hech qanday yangi xabarlar mavjud emas.',
      'home_title': 'Sog\'ligingiz haqida qayg\'uramiz',
      'home_subtitle': 'Eng yaxshi shifokorlar va tibbiy xizmatlar bir joyda.',
    },
    'ru': {
      'welcome': 'Добро пожаловать',
      'select_language': 'Выберите язык',
      'phone_input_title': 'Введите номер телефона',
      'phone_input_subtitle': 'Нам нужен ваш номер для защиты аккаунта.',
      'continue': 'Продолжить',
      'otp_title': 'Введите 6-значный код',
      'otp_subtitle': 'Код подтверждения отправлен на номер: ',
      'register_title': 'Регистрация',
      'first_name': 'Имя',
      'last_name': 'Фамилия',
      'province': 'Область',
      'district': 'Район',
      'birth_date': 'Дата рождения',
      'home': 'Главная',
      'appointments': 'Прием',
      'messages': 'Сообщения',
      'profile': 'Профиль',
      'settings': 'Настройки',
      'logout': 'Выйти',
      'view_profile': 'Посмотреть профиль',
      'personal_info': 'Личные данные',
      'payments': 'Платежи',
      'security': 'Безопасность',
      'change_language': 'Смена языка',
      'help': 'Помощь',
      'messages_empty_title': 'Сообщений нет!',
      'messages_empty_desc': 'У вас пока нет новых сообщений.',
      'home_title': 'Мы заботимся о вашем здоровье',
      'home_subtitle': 'Лучшие врачи и медицинские услуги в одном месте.',
    },
    'en': {
      'welcome': 'Welcome',
      'select_language': 'Select Language',
      'phone_input_title': 'Enter phone number',
      'phone_input_subtitle': 'We need your number to protect your account.',
      'continue': 'Continue',
      'otp_title': 'Enter 6-digit code',
      'otp_subtitle': 'Verification code sent to: ',
      'register_title': 'Registration',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'province': 'Province',
      'district': 'District',
      'birth_date': 'Birth Date',
      'home': 'Home',
      'appointments': 'Booking',
      'messages': 'Messages',
      'profile': 'Profile',
      'settings': 'Settings',
      'logout': 'Log out',
      'view_profile': 'View profile',
      'personal_info': 'Personal information',
      'payments': 'Payments',
      'security': 'Security',
      'change_language': 'Change language',
      'help': 'Help',
      'messages_empty_title': 'No messages found!',
      'messages_empty_desc': 'You don\'t have any new messages yet.',
      'home_title': 'We care about your health',
      'home_subtitle': 'Best doctors and medical services in one place.',
    }
  };

  static String get(String key) {
    return _translations[currentLocale]?[key] ?? key;
  }
}
